#!/usr/bin/php -q
<?php
/**
 * Command line utility for alchemy framework
 */
require_once __DIR__ . '/app/Application.php';
$app = new \alchemy\future\util\Console(__DIR__ . '/future/util');
//$app->addRoute('generate:{$what}', )
$app->onURI('locale:{$func:.*}', 'util\command\Locale::{$func}');
$app->onURI('help', 'util\command\Common::help');
$app->onURI('exit', 'util\command\Common::close');
$app->onURI('close', 'util\command\Common::close');
$app->onURI('*','util\command\Common::error');
$app->onStartup('util\command\Common::help');
$app->onError('util\command\Common::error');
$app->run();