#!/usr/bin/php -q
<?php
/**
 * Command line utility for alchemy framework
 */
require_once __DIR__ . '/app/Application.php';
$app = new \alchemy\app\Console(__DIR__ . '/app/util');
//$app->addRoute('generate:{$what}', )
$app->addRoute('locale:{$func:.*}', 'util\command\Locale::{$func}');
$app->addRoute('help', 'util\command\Common::help');
$app->addRoute('exit', 'util\command\Common::close');
$app->addRoute('close', 'util\command\Common::close');
$app->addRoute('*','util\command\Common::error');
$app->onStartup('util\command\Common::help');
$app->onError('util\command\Common::error');
$app->run();